weekly_assignment:
  outputs:
    dev:
      dataset: nyc_taxi
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /opt/airflow/dags/dbts/weekly_assignment/service_account.json
      location: US
      method: service-account
      priority: interactive
      project: brave-sonar-400508
      threads: 3
      type: bigquery
  target: dev